// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoFinal.Data;

#nullable disable

namespace ProyectoFinal.Migrations
{
    [DbContext(typeof(ProyectoFinalContext))]
    [Migration("20231203061510_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.14");

            modelBuilder.Entity("ProyectoFinal.Models.Anfitrion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("DineroGastado")
                        .HasColumnType("REAL");

                    b.Property<int>("NoFiestas")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Anfitrion");
                });

            modelBuilder.Entity("ProyectoFinal.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("ProyectoFinal.Models.Dj", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<double>("Paga")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Dj");
                });

            modelBuilder.Entity("ProyectoFinal.Models.Evento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AnfitrionId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DjId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("NoInvitados")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PagoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AnfitrionId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("DjId");

                    b.HasIndex("PagoId");

                    b.ToTable("Evento");
                });

            modelBuilder.Entity("ProyectoFinal.Models.InformacionPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("NoTarjeta")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titular")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("InformacionPago");
                });

            modelBuilder.Entity("ProyectoFinal.Models.Evento", b =>
                {
                    b.HasOne("ProyectoFinal.Models.Anfitrion", "Anfitrion")
                        .WithMany()
                        .HasForeignKey("AnfitrionId");

                    b.HasOne("ProyectoFinal.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId");

                    b.HasOne("ProyectoFinal.Models.Dj", "Dj")
                        .WithMany()
                        .HasForeignKey("DjId");

                    b.HasOne("ProyectoFinal.Models.InformacionPago", "Pago")
                        .WithMany()
                        .HasForeignKey("PagoId");

                    b.Navigation("Anfitrion");

                    b.Navigation("Categoria");

                    b.Navigation("Dj");

                    b.Navigation("Pago");
                });
#pragma warning restore 612, 618
        }
    }
}
